# Generated by Django 2.1.7 on 2019-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_auto_20190325_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translations',
            new_name='Ger_Eng_Dict',
        ),
    ]
