# Generated by Django 2.1.7 on 2019-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_auto_20190325_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg1', models.CharField(max_length=4096)),
                ('msg2', models.CharField(max_length=4096)),
                ('fromLang', models.CharField(max_length=256)),
                ('toLang', models.CharField(max_length=256)),
            ],
        ),
    ]
