# Generated by Django 2.1.7 on 2019-04-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_auto_20190330_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guiinfo',
            old_name='english',
            new_name='msg1',
        ),
        migrations.RenameField(
            model_name='guiinfo',
            old_name='german',
            new_name='msg2',
        ),
    ]
